using System;
using System.Collections.Generic;
using UnityEngine;

namespace Game.Cube
{
    /// <summary>
    /// The modules the layout draws from. Town modules are fixed and indexed by cell (row-major,
    /// y * N + x); each science theme lists a pool. Generated by Cube > Build Module Library.
    /// </summary>
    public class ModuleLibrary : ScriptableObject, IModuleCatalog
    {
        [Serializable]
        public class ThemePool
        {
            public Theme Theme;
            public List<ScreenModule> Modules = new List<ScreenModule>();
        }

        [SerializeField] private List<ScreenModule> townModules = new List<ScreenModule>();
        [SerializeField] private List<ThemePool> sciencePools = new List<ThemePool>();

        public IReadOnlyList<ScreenModule> TownModules => townModules;
        public IReadOnlyList<ThemePool> SciencePools => sciencePools;

        public void Set(List<ScreenModule> town, List<ThemePool> pools)
        {
            townModules = town;
            sciencePools = pools;
        }

        /// <summary>The fixed Town module for a cell. Wraps if N needs more cells than the library has.</summary>
        public ScreenModule TownModule(Vector2Int cell, int faceSize)
        {
            if (townModules.Count == 0) return null;
            int index = cell.y * faceSize + cell.x;
            return townModules[index % townModules.Count];
        }

        public IReadOnlyList<ScreenModule> Pool(Theme theme)
        {
            foreach (ThemePool pool in sciencePools)
                if (pool.Theme == theme) return pool.Modules;
            return Array.Empty<ScreenModule>();
        }

        public ScreenModule Module(Theme theme, int index) => Pool(theme)[index];

        // ---- IModuleCatalog (what CubeLayout needs, without touching scenes) ----

        public int PoolSize(Theme theme) => Pool(theme).Count;

        public int CoreSlotCount(Theme theme, int moduleIndex) => Pool(theme)[moduleIndex].CoreEntranceCount;
    }
}
