using UnityEngine;

namespace Game.Cube
{
    /// <summary>
    /// An item as data: one per built theme (its home face). Gates are bound to an ItemDefinition, so a
    /// face story replaces its placeholder item asset without touching the placer or the gates.
    /// Placeholder assets are generated by Cube > Build Item Catalog.
    /// </summary>
    [CreateAssetMenu(menuName = "Cube/Item Definition", fileName = "Item")]
    public class ItemDefinition : ScriptableObject
    {
        [SerializeField] private string id;
        [SerializeField] private string displayName;
        [SerializeField] private Theme homeTheme;
        [SerializeField] private Color placeholderColor = Color.white;

        [Tooltip("Swing reach (world units) while this item is equipped; 0 keeps the player's default reach.")]
        [SerializeField, Min(0f)] private float attackReach;

        /// <summary>Stable identifier (e.g. "biology-item").</summary>
        public string Id => id;

        public string DisplayName => displayName;

        /// <summary>The theme (face) this item belongs to; its pickup sits on that face.</summary>
        public Theme HomeTheme => homeTheme;

        /// <summary>Colour used for the placeholder pickup and its gates until real art exists.</summary>
        public Color PlaceholderColor => placeholderColor;

        /// <summary>
        /// Reach of the player's swing while this item is equipped (0 = the default reach). The thin beak uses
        /// it to press distant buttons and pollinate flowers.
        /// </summary>
        public float AttackReach
        {
            get => attackReach;
            set => attackReach = Mathf.Max(0f, value);
        }

        public void Set(string itemId, string name, Theme home, Color color)
        {
            id = itemId;
            displayName = name;
            homeTheme = home;
            placeholderColor = color;
        }

        /// <summary>Creates an unsaved runtime instance (tests and tools).</summary>
        public static ItemDefinition Create(string itemId, string name, Theme home, Color color)
        {
            var item = CreateInstance<ItemDefinition>();
            item.name = name;
            item.Set(itemId, name, home, color);
            return item;
        }

        public override string ToString() => string.IsNullOrEmpty(displayName) ? name : displayName;
    }
}
