using System.Collections.Generic;
using UnityEngine;

namespace Game.Cube
{
    /// <summary>
    /// The items of the run: one ItemDefinition per built theme, looked up by home theme. CubeWorld
    /// resolves ItemPlacement's theme keys to definitions through this. Generated by Cube > Build Item Catalog.
    /// </summary>
    public class ItemCatalog : ScriptableObject
    {
        [SerializeField] private List<ItemDefinition> items = new List<ItemDefinition>();

        public IReadOnlyList<ItemDefinition> Items => items;

        public void Set(List<ItemDefinition> definitions) => items = definitions;

        /// <summary>The item whose home is the given theme, or null.</summary>
        public ItemDefinition ForTheme(Theme theme)
        {
            foreach (ItemDefinition item in items)
                if (item != null && item.HomeTheme == theme) return item;
            return null;
        }

        /// <summary>Home themes of every item, in catalog order.</summary>
        public List<Theme> Themes()
        {
            var themes = new List<Theme>();
            foreach (ItemDefinition item in items)
                if (item != null && !themes.Contains(item.HomeTheme)) themes.Add(item.HomeTheme);
            return themes;
        }
    }
}
