using System.Collections.Generic;
using UnityEngine;

namespace Game.Cube
{
    /// <summary>
    /// The items of the run: one ItemDefinition per built theme, looked up by home theme. A theme may also
    /// have variants (Biology: the thin and thick beak); then each run uses one of them, picked by a seeded
    /// roll (ItemVariants.Roll), and the variant replaces the theme's base entry for that run. ItemPlacement
    /// still sees one logical item per theme. CubeWorld resolves ItemPlacement's theme keys to definitions
    /// through ItemFor. Generated by Cube > Build Item Catalog.
    /// </summary>
    public class ItemCatalog : ScriptableObject
    {
        [SerializeField] private List<ItemDefinition> items = new List<ItemDefinition>();

        [Tooltip("Per-run variants of a theme's item, in roll order (variant index = position among its theme's variants).")]
        [SerializeField] private List<ItemDefinition> variants = new List<ItemDefinition>();

        public IReadOnlyList<ItemDefinition> Items => items;

        /// <summary>Every variant of every theme, in catalog order.</summary>
        public IReadOnlyList<ItemDefinition> Variants => variants;

        public void Set(List<ItemDefinition> definitions) => items = definitions;

        public void SetVariants(List<ItemDefinition> definitions) => variants = definitions ?? new List<ItemDefinition>();

        /// <summary>The base item whose home is the given theme, or null (ignores variants).</summary>
        public ItemDefinition ForTheme(Theme theme)
        {
            foreach (ItemDefinition item in items)
                if (item != null && item.HomeTheme == theme) return item;
            return null;
        }

        /// <summary>The variants of a theme's item, in roll order (empty when it has none).</summary>
        public List<ItemDefinition> VariantsOf(Theme theme)
        {
            var list = new List<ItemDefinition>();
            foreach (ItemDefinition item in variants)
                if (item != null && item.HomeTheme == theme) list.Add(item);
            return list;
        }

        /// <summary>The rolled variant index of a theme for a seed, or -1 when the theme has no variants.</summary>
        public int RollVariant(int seed, Theme theme)
        {
            int count = VariantsOf(theme).Count;
            return count == 0 ? -1 : ItemVariants.Roll(seed, theme, count);
        }

        /// <summary>
        /// The item a run with this seed uses for a theme: the rolled variant when the theme has variants,
        /// otherwise the base item. Null when the catalog has neither.
        /// </summary>
        public ItemDefinition ItemFor(Theme theme, int seed)
        {
            List<ItemDefinition> list = VariantsOf(theme);
            if (list.Count == 0) return ForTheme(theme);
            return list[ItemVariants.Roll(seed, theme, list.Count)];
        }

        /// <summary>The variants of a theme the run does not use (empty without variants).</summary>
        public List<ItemDefinition> UnrolledVariants(Theme theme, int seed)
        {
            List<ItemDefinition> list = VariantsOf(theme);
            if (list.Count > 0) list.RemoveAt(ItemVariants.Roll(seed, theme, list.Count));
            return list;
        }

        /// <summary>Variant count per theme that has variants (what ItemPlacement and the sweep need).</summary>
        public Dictionary<Theme, int> VariantCounts()
        {
            var counts = new Dictionary<Theme, int>();
            foreach (ItemDefinition item in variants)
            {
                if (item == null) continue;
                counts.TryGetValue(item.HomeTheme, out int n);
                counts[item.HomeTheme] = n + 1;
            }
            return counts;
        }

        /// <summary>Home themes of every item (base entries, then variant-only themes), in catalog order.</summary>
        public List<Theme> Themes()
        {
            var themes = new List<Theme>();
            foreach (ItemDefinition item in items)
                if (item != null && !themes.Contains(item.HomeTheme)) themes.Add(item.HomeTheme);
            foreach (ItemDefinition item in variants)
                if (item != null && !themes.Contains(item.HomeTheme)) themes.Add(item.HomeTheme);
            return themes;
        }
    }
}
